Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 200

Layout/EndOfLine:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false
